### PR TITLE
Fix issue with incorrect `database_size` when requesting a smaller `shared_file_size`

### LINKED ISSUE #28: [5.0] Fix chainbase issue when shrinking the database size.
Along with the changes for `map_private` mode, an issue sneaked in that Matt identified in his testing.

When the user tries to shrink the chainbase db (i.e. sets `chain-state-db-size-mb` to a lower number) and restarts nodeos, we internally keep track of a wrong `database_size`, which leads to possible crashes.

### PR DESCRIPTION
**Pull request by greg7mdp**
Resolves #28 .

This makes sure our `_database_size` member tracks the actual size of the file we are mmap'ing into memory.

### CODE REVIEW

File: src/pinnable_mapped_file.cpp [hunk 1]
```diff
@@ -134,7 +134,8 @@ pinnable_mapped_file::pinnable_mapped_file(const std::filesystem::path& dir, boo
             std::filesystem::resize_file(_data_file_path, shared_file_size);
          }
          else if(shared_file_size < existing_file_size) {
-             std::cerr << "CHAINBASE: \"" << _database_name << "\" requested size of " << shared_file_size << " is less than "
+            _database_size = existing_file_size;
+            std::cerr << "CHAINBASE: \"" << _database_name << "\" requested size of " << shared_file_size << " is less than "
```
Comment (heifner) [inline src/pinnable_mapped_file.cpp:138]: I think this code would be clearer if the constructor used `_database_size` instead of `shared_file_size`.

Comment (greg7mdp) [reply src/pinnable_mapped_file.cpp:138]: I don't disagree that it is not very clear. This is for a 5.0 issue, so I'd rather make a small change.

Also we have this (maybe unintuitive) behavior that we allow the user to request a smaller size, but if the database already exist and is larger we just use the existing size without shrinking it (which would be difficult).

**Review by heifner — APPROVED** [review]

**Review by spoonincode — APPROVED** [review]
